Twitter/Twitter/Models/Query.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;


namespace Twitter.Models
{
    class Query
    {
       
        public string sentiment_label;
        public string tweet_text;
    }
}

Twitter/Twitter/Controllers/QueryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using Newtonsoft.Json;
using System.Web.Script.Serialization;
using Twitter.Models;
using System.IO;

namespace Twitter.Controllers
{
    public class StringTable
    {
        public string[] ColumnNames { get; set; }
        public string[,] Values { get; set; }
    }

    public class QueryController : Controller
    {
        // GET: Query

        public ActionResult Index()
        {
            return View();
        }
        string result;
        string tw;

        public async Task<ActionResult> Welcome(string lname)
        {
            tw = lname;
            result = await InvokeRequestResponseService(lname).ConfigureAwait(false); ;
            if (result != "")
            {
                ViewBag.Error = false;
                var resultss = JsonConvert.DeserializeObject<RootObject>(result);
                if (resultss.Results.output1.value.Values[0][0] == "negative")
                {
                    resultss.Results.output1.value.Values[0][1] =( 1 - Convert.ToDouble( resultss.Results.output1.value.Values[0][1])).ToString();
                }
                ViewBag.Tweet = tw;
                ViewBag.Response = string.Format("{0} with Probability {1:0.0000}", resultss.Results.output1.value.Values[0][0], resultss.Results.output1.value.Values[0][1]);
            }else
            {
                ViewBag.Error = true;
            }
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "This is About Artificial Intelligence Cource Project, Twitter Sentiment Data Analysis";

            return View();
        }
        public ActionResult GetPdf()
        {
            var fileStream = new FileStream("~/Content/files/Report.pdf" ,
                                             FileMode.Open,
                                             FileAccess.Read
                                           );
            var fsResult = new FileStreamResult(fileStream, "application/pdf");
            return fsResult;
        }
        async Task<string> InvokeRequestResponseService(string tweet)
        {
            using (var client = new HttpClient())
            {
                var scoreRequest = new
                {

                    Inputs = new Dictionary<string, StringTable>() {
                        {
                            "input1",
                            new StringTable()
                            {
                                ColumnNames = new string[] {"sentiment_label", "tweet_text"},
                                Values = new string[,] {  { "0", tweet } }
                            }
                        },
                    },
                    GlobalParameters = new Dictionary<string, string>()
                    {
                    }
                };
                const string apiKey = "5insn0xEIFCYXaFhfWmpPZ4Yt60DXgXtoW73KurxlkZ98H5/jWPiHKcuDnuw3fnlBs8JAZEs1Y15ZYMLb53ZCw=="; // Replace this with the API key for the web service
                client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", apiKey);

                client.BaseAddress = new Uri("https://ussouthcentral.services.azureml.net/workspaces/d8b7f0bf4d2e4a7f95fc241fcd2792fd/services/7f8db9ba819b4935ab8418c9c8d10090/execute?api-version=2.0&details=true");

                // WARNING: The 'await' statement below can result in a deadlock if you are calling this code from the UI thread of an ASP.Net application.
                // One way to address this would be to call ConfigureAwait(false) so that the execution does not attempt to resume on the original context.
                // For instance, replace code such as:
                //      result = await DoSomeTask()
                // with the following:
                //      result = await DoSomeTask().ConfigureAwait(false)


                HttpResponseMessage response = await client.PostAsJsonAsync("", scoreRequest).ConfigureAwait(false);

                if (response.IsSuccessStatusCode)
                {
                    string result = await response.Content.ReadAsStringAsync().ConfigureAwait(false);
                    
                    return result;
                    //Console.ReadKey();
                }
                else
                {
                    //Console.WriteLine(string.Format("The request failed with status code: {0}", response.StatusCode));

                    // Print the headers - they include the requert ID and the timestamp, which are useful for debugging the failure
                   // Console.WriteLine(response.Headers.ToString());

                    string responseContent = await response.Content.ReadAsStringAsync().ConfigureAwait(false);
                    return "Fail";
                }
            }
        }
    }
}

Twitter/Twitter/Views/Query/About.cshtml
@{
    ViewBag.Title = "About";
}
<h1>@ViewBag.Title</h1>
<h3>
    Project  Members:
</h3>
<h4>
   
<dd class="col-sm-5">Rajan Vaghela [UG201310039]<br>Kshitij Minoch [UG201310043]</dd>
</h4>
<br><br><br><br>
<p class="lead left">
 
    This is website about Artificial Intelligence Course Project, Twitter Sentiment Data Analysis.<br>
    Analysis is based on Two Class SVM implemented using Azure ML.<br>
    Project Report can be found <a href="~/files/Report.pdf" target="_blank">here</a>

</p>

Twitter/Twitter/Views/Query/Index.cshtml
@{
    ViewBag.Title= "Home - Twitter Sentiment Data Analysis";
}

    <h2 >Twitter Sentiment Analysis</h2>
    <p class="lead">Enter Any Query For Sentiment Analysis</pclass="lead"><br>

        @using (Html.BeginForm("Welcome", "Query", FormMethod.Post))
        {

            
            <div class="form-group">
                <label for="inputlg">Enter Tweets:</label>
                <textarea name="lname" class="form-control" rows="5" id="comment"></textarea>
                <br>
                <input type="submit" value="Submit" class="btn btn-primary">
              
            </div>
            

            
        }
    

Twitter/Twitter/Views/Query/Welcome.cshtml
@{
    ViewBag.Title = "Response";
}
<h2>Response</h2>
@if (ViewBag.Error == true){
     <p>Error</p>
}

else
{

    <div class="form-group">
        <label for="comment">Tweet:</label>
        <textarea readonly class="form-control" rows="5" id="comment">@ViewBag.Tweet</textarea>
    </div>
   

    <div>
    <h4>   Sentiment Analysis Response:<.br><pre> @ViewBag.Response </pre></h4>
        </div>
}

Twitter/Twitter/Views/Query/_LayoutPage1.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    <script type="text/javascript">
        var appInsights=window.appInsights||function(config){
            function r(config){t[config]=function(){var i=arguments;t.queue.push(function(){t[config].apply(t,i)})}}var t={config:config},u=document,e=window,o="script",s=u.createElement(o),i,f;for(s.src=config.url||"//az416426.vo.msecnd.net/scripts/a/ai.0.js",u.getElementsByTagName(o)[0].parentNode.appendChild(s),t.cookie=u.cookie,t.queue=[],i=["Event","Exception","Metric","PageView","Trace","Ajax"];i.length;)r("track"+i.pop());return r("setAuthenticatedUserContext"),r("clearAuthenticatedUserContext"),config.disableExceptionTracking||(i="onerror",r("_"+i),f=e[i],e[i]=function(config,r,u,e,o){var s=f&&f(config,r,u,e,o);return s!==!0&&t["_"+i](config,r,u,e,o),s}),t
        }({
            instrumentationKey:"6cbf7638-7941-4977-897e-cb99f5c398c0"
        });

        window.appInsights=appInsights;
        appInsights.trackPageView();
    </script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Twitter Sentiment Analysis", "Index", "Query", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Query")</li>
                    <li>@Html.ActionLink("About", "About", "Query")</li>
                    
                </ul>
                
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        
    </div>


    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>